 CREATE TABLE "SYSTEM"."TB_ATRIBUICAO" 
   (	"MATRICULA_FUNC" VARCHAR2(11 BYTE), 
	"ID_PROJETO" VARCHAR2(5 BYTE), 
	"ID_PAPEL" VARCHAR2(5 BYTE)
   )


  CREATE TABLE "SYSTEM"."TB_COLABORADOR" 
   (	"MATRICULA_FUNC" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DEPARTAMENTO" VARCHAR2(100 BYTE), 
	"CPF" VARCHAR2(11 BYTE), 
	"NOME_FUNC" VARCHAR2(150 BYTE), 
	"SALARIO" NUMBER(20,0), 
   )

CREATE TABLE "SYSTEM"."TB_DEPARTAMENTO" 
   (	"SIGLA_DEPTO" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"NOME_DEPARTAMENTO" VARCHAR2(30 BYTE), 
	"CHEFE_DEPARTAMENTO" VARCHAR2(30 BYTE), 
	"DEPTO_SUPERIOR" VARCHAR2(30 BYTE), 
   )

CREATE TABLE "SYSTEM"."TB_DEPENDENTE" 
   (	"CPF" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"NOME_FUNCIONARIO" VARCHAR2(50 BYTE), 
	"NOME_DEPENDENTE" VARCHAR2(50 BYTE), 
	"DATA_NASCIMENTO" DATE, 
	"PARENTESCO" VARCHAR2(15 BYTE),
   )

  CREATE TABLE "SYSTEM"."TB_EMAIL_COLABORADOR" 
   (	"MATRICULA_FUNC" VARCHAR2(11 BYTE), 
	"EMAIL_PESSOAL" VARCHAR2(40 BYTE), 
	"EMAIL_CORP" VARCHAR2(40 BYTE)
   )


  CREATE TABLE "SYSTEM"."TB_ENDERECO_COLABORADOR" 
   (	"MATRICULA_FUNC" VARCHAR2(11 BYTE), 
	"LOGRADOURO" VARCHAR2(80 BYTE), 
	"NUMERO" NUMBER(10,0), 
	"COMPLEMENTO" VARCHAR2(30 BYTE), 
	"BAIRRO" VARCHAR2(30 BYTE), 
	"CIDADE" VARCHAR2(30 BYTE), 
	"ESTADO" VARCHAR2(2 BYTE), 
	"CEP" VARCHAR2(9 BYTE)
   )


  CREATE TABLE "SYSTEM"."TB_PAPEL" 
   (	"ID_PAPEL" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"NOME_PAPEL" VARCHAR2(20 BYTE), 
	 CONSTRAINT "TB_PAPEL_PK" PRIMARY KEY ("ID_PAPEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   )

  CREATE TABLE "SYSTEM"."TB_PROJETO" 
   (	"ID_PROJETO" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"NOME_PROJETO" VARCHAR2(30 BYTE), 
	"MATRICULA_FUNC" VARCHAR2(11 BYTE), 
	"PERIODO_INICIO" DATE, 
	"PERIODO_FIM" DATE, 
	 CONSTRAINT "TB_PROJETO_PK" PRIMARY KEY ("ID_PROJETO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   )

  CREATE TABLE "SYSTEM"."TB_TELEFONE_COLABORADOR" 
   (	"MATRICULA_FUNC" VARCHAR2(11 BYTE), 
	"TELEFONE_1" VARCHAR2(11 BYTE), 
	"TELEFONE_2" VARCHAR2(11 BYTE)
   )

